@Uzma_Jawed



---


### 📘 Vectors & Matrices for AI: Basics

---


A Notebook for Linear Algebra Fundamentals


---



In [ ]:
# First, let's import necessary libraries
import numpy as np
import matplotlib.pyplot as plt



---


### ✅ 1. Vectors


---


🔹 What is a Vector?

A vector is a mathematical object with magnitude and direction, represented as an array of numbers.

In AI, vectors represent data points (e.g., word embeddings, feature vectors).

Example: [3, 4] is a 2D vector.


---


🔹 Vector Representation in Python
___

In [ ]:
# Creating vectors with NumPy
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])

print("Vector 1:", vector_1)
print("Vector 2:", vector_2)

Vector 1: [1 2 3]
Vector 2: [4 5 6]




---


🔹 Vector Operations


---


Addition


---



In [ ]:
vector_sum = vector_1 + vector_2
print("Sum:", vector_sum)

Sum: [5 7 9]




---


Scalar Multiplication

---



In [ ]:
scalar = 2
scaled_vector = scalar * vector_1
print("Scaled Vector:", scaled_vector)

Scaled Vector: [2 4 6]




---


Dot Product (Important for AI!)


---



In [ ]:
dot_product = np.dot(vector_1, vector_2)
print("Dot Product:", dot_product)

Dot Product: 32





---


### 🔹 What is a Matrix?


---


A matrix is a 2D array of numbers, used in AI for transformations (e.g., weights in a neural network).

Example:
A =

 [1 2
  
3 4]
___



---


### 🔹 Matrix Representation in Python


---



In [ ]:
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", matrix_A)
print("Matrix B:\n", matrix_B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]




---


### 🔹 Matrix Operations


---


Addition & Subtraction
___

In [ ]:
matrix_sum = matrix_A + matrix_B
print("Sum:\n", matrix_sum)

Sum:
 [[ 6  8]
 [10 12]]




---


Matrix Multiplication (Key in AI!)


---



In [ ]:
matrix_product = np.matmul(matrix_A, matrix_B)
print("Product:\n", matrix_product)

Product:
 [[19 22]
 [43 50]]




---


Transpose (Flips rows & columns)


---



In [ ]:
transpose_A = matrix_A.T
print("Transpose of A:\n", transpose_A)

Transpose of A:
 [[1 3]
 [2 4]]




---


✅ 3. Practice Section
✏️ Exercise 1: Vector Operations
Compute:

3 * vector_1 + vector_2

Dot product of vector_1 and [0, 1, 0]

✏️ Exercise 2: Matrix Operations
Given:
C =

 [2 0

  0 2]

Compute:

C * matrix_A (element-wise)

C @ matrix_A (matrix multiplication)

✏️ Exercise 3: Transpose Challenge

Create a 3x2 matrix and find its transpose.
___



🎯 Final Notes
Vectors & matrices are building blocks for AI (e.g., tensors in PyTorch).

Next Steps: Learn about determinants, inverses, and eigenvalues for deeper ML understanding!


---

